### ISSUE TITLE
Can't use with Webpack

### ISSUE THREAD

**Issue by DannySantos** [hanami/ujs#6]
I haven't been able to figure out how to serve the `hanami-ujs` library using Webpack, the docs currently assume you are using `Hanami::Assets`. 

I'm currently trying to get Hanami working with StimulusJS, and they seem to have come up with a method of optionally serving their assets using Webpack:

https://github.com/stimulusjs/stimulus/tree/6946174b07b8891c8fab0ef7509842d950741c34/packages/%40stimulus/webpack-helpers

I can't figure out exactly how they're doing it, but thought I'd raise the issue in case implementing something similar here is of interest to anyone.

**Comment by cllns** [comment]
This project bundles up the [`vanilla-ujs`](https://github.com/hauleth/vanilla-ujs) code for use with `Hanami::Assets`. If you want to go with webpack instead of `Hanami::Assets`, then you don't need this gem :) Instead, looking to getting `vanilla-ujs` itself.

Closing this as I'm pretty sure this will solve your problem, but feel free to open it again if needed. 🌸
